include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Const enforcement
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - unnecessary_const

    # Final enforcement
    - prefer_final_locals
    - prefer_final_fields
    - prefer_final_in_for_each

    # Production safety & hygiene
    - avoid_print
    - always_declare_return_types
    - avoid_returning_null_for_void
    - unnecessary_this
    - avoid_relative_lib_imports
    - unawaited_futures
    - cancel_subscriptions
    - close_sinks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_string_interpolations
    - use_build_context_synchronously
