// CI stub for firebase_options.dart.
//
// This file contains obviously-fake placeholder values used only so that
// `flutter analyze` and `flutter test` can compile on CI runners that do not
// have a real Firebase project configured.
//
// The real `firebase_options.dart` is generated by the FlutterFire CLI
// (`flutterfire configure`) and kept out of version control via .gitignore
// so that per-environment credentials are never committed.
//
// How to use on CI:
//   cp skiflux_mobile_app_v2/lib/firebase_options_ci_stub.dart \
//      skiflux_mobile_app_v2/lib/firebase_options.dart
//
// The app's `_initFirebase()` in main.dart wraps Firebase.initializeApp in a
// try/catch, so a failed init with these placeholder credentials degrades
// gracefully to "FCM unavailable" rather than crashing.

// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      default:
        return _android;
    }
  }

  // CI placeholder — not real credentials. Replace with the output of
  // `flutterfire configure` for any real environment.
  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'ci-placeholder-api-key',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'skiflux-ci-placeholder',
    storageBucket: 'skiflux-ci-placeholder.firebasestorage.app',
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'ci-placeholder-api-key',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'skiflux-ci-placeholder',
    storageBucket: 'skiflux-ci-placeholder.firebasestorage.app',
    iosBundleId: 'com.skiflux.mobileApp',
  );
}
